services:
  b3-engine:
    build: .
    container_name: b3_analytics
    volumes:
      - .:/app
      - ./data:/data  # Your .duckdb file and B3 TXTs go here
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1